CC = gcc

all:
	gcc mid01.c -o mid01
	gcc -c binp.c -o binp.o 
	gcc mid02.c binp.o -lm -o mid02 
	gcc mid03.c -o mid03
	gcc mid04.c -o mid04
	gcc -c triangle.c -o triangle.o 
	gcc mid05.c triangle.o -lm -o mid05



