CC = gcc

all:
	gcc -c myfunc.c -o myfunc.o
	gcc hw0301.c myfunc.o -o hw0301
	gcc -c mystddev.c -o mystddev.o
	gcc hw0302.c mystddev.o -lm -o hw0302
	gcc -c resistance.c -o resistance.o 
	gcc hw0303.c resistance.o -lm -o hw0303
	gcc -c hanoi.c -o hanoi.o
	gcc hw0304-1.c hanoi.o -lm -o hw0304-1
	gcc hw0304-2.c hanoi.o -lm -o hw0304-2
	gcc -c smallten.c -o smallten.o
	gcc -c logic.c -o logic.o
	gcc hw0305.c logic.o smallten.o -o hw0305


